# Generated by Django 4.1 on 2022-10-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugs_domain', models.CharField(max_length=20)),
                ('bugs_date', models.DateField()),
                ('bugs_owner', models.CharField(max_length=40)),
                ('bugs_name', models.CharField(max_length=40)),
                ('bugs_description', models.CharField(max_length=500)),
                ('bugs_blocking', models.BooleanField(default=False)),
                ('bugs_media', models.FileField(blank=True, null=True, upload_to='Videos o archivos errores')),
                ('bugs_image', models.ImageField(blank=True, null=True, upload_to='Errores')),
            ],
        ),
        migrations.CreateModel(
            name='investigations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=40)),
                ('investigation_owner', models.CharField(max_length=40)),
                ('investigation_name', models.CharField(max_length=40)),
                ('investigation_date', models.DateField()),
                ('investigation_overview', models.CharField(max_length=500)),
                ('investigation_media', models.FileField(upload_to='Investigaciones')),
            ],
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips_owner', models.CharField(max_length=40)),
                ('tips_name', models.CharField(max_length=250)),
                ('tips_description', models.CharField(max_length=500)),
                ('tips_date', models.DateField()),
                ('tips_email', models.EmailField(max_length=254)),
                ('tips_media', models.FileField(blank=True, null=True, upload_to='Refuerzos')),
                ('tips_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
