# Generated by Django 4.1 on 2022-10-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigations',
            name='domain_name',
            field=models.CharField(max_length=40, verbose_name='Nombre del Dominio'),
        ),
    ]
