# Generated by Django 4.1 on 2022-10-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPApp', '0002_alter_investigations_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigations',
            name='investigation_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link de la Investigación'),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='bugs_blocking',
            field=models.BooleanField(default=False, verbose_name='¿El error es bloqueante?'),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='bugs_date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='bugs_description',
            field=models.CharField(max_length=500, verbose_name='Descripción del error'),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='bugs_domain',
            field=models.CharField(max_length=20, verbose_name='Nombre del Dominio'),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='bugs_image',
            field=models.ImageField(blank=True, null=True, upload_to='Errores', verbose_name='Imagen del error'),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='bugs_media',
            field=models.FileField(blank=True, null=True, upload_to='Videos o archivos errores', verbose_name='Video del error'),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='bugs_name',
            field=models.CharField(max_length=40, verbose_name='Nombre o codigo del error'),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='bugs_owner',
            field=models.CharField(max_length=40, verbose_name='Nombre del colaborador'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='investigation_date',
            field=models.DateField(verbose_name='Fecha de Investigación'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='investigation_media',
            field=models.FileField(upload_to='Investigaciones', verbose_name='Archivo de la investigacion'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='investigation_name',
            field=models.CharField(max_length=40, verbose_name='Nombre de la Investigación'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='investigation_overview',
            field=models.CharField(max_length=500, verbose_name='Resumen de la Investigación'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='investigation_owner',
            field=models.CharField(max_length=40, verbose_name='Creador'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='tips_date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='tips_description',
            field=models.CharField(max_length=500, verbose_name='Descripción del refuerzo'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='tips_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='tips_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link del Refuerzo'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='tips_media',
            field=models.FileField(blank=True, null=True, upload_to='Refuerzos', verbose_name='Archivo del Refuerzo'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='tips_name',
            field=models.CharField(max_length=250, verbose_name='Nombre del refuerzo'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='tips_owner',
            field=models.CharField(max_length=40, verbose_name='Creador del refuerzo'),
        ),
    ]
